CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "hashed_password" VARCHAR(256) NOT NULL,
    "salt" VARCHAR(20) NOT NULL,
    "first_name" VARCHAR(50) NOT NULL,
    "last_name" VARCHAR(50) NOT NULL,
    "date_of_birth" TIMESTAMP NOT NULL,
    "email" VARCHAR(50) NOT NULL,
    "user_name" VARCHAR(50) NOT NULL
);
CREATE TABLE "post" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "content_text" VARCHAR(500),
    "content_image_path" VARCHAR(255),
    "user_id" INT NOT NULL,
    "visible" BOOL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "deleted_at" TIMESTAMP
);
CREATE TABLE "following" (
    "user_id" INT NOT NULL,
    "friend_id" INT NOT NULL,
    PRIMARY KEY ("user_id", "friend_id")
);
CREATE TABLE "comment" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "content" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "user_id" INT NOT NULL,
    "post_id" INT NOT NULL
);
CREATE TABLE "like" (
    "user_id" INT NOT NULL,
    "post_id" INT NOT NULL,
    PRIMARY KEY ("post_id", "user_id")
);
CREATE INDEX "idx_username" ON "user" ("user_name");
ALTER TABLE "post"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "following"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "following"
ADD FOREIGN KEY ("friend_id") REFERENCES "user" ("id");
ALTER TABLE "comment"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "comment"
ADD FOREIGN KEY ("post_id") REFERENCES "post" ("id");
ALTER TABLE "like"
ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");
ALTER TABLE "like"
ADD FOREIGN KEY ("post_id") REFERENCES "post" ("id");