// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32        `json:"id"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    int32        `json:"user_id"`
	PostID    int32        `json:"post_id"`
}

type Following struct {
	UserID   int32 `json:"user_id"`
	FriendID int32 `json:"friend_id"`
}

type Like struct {
	UserID int32 `json:"user_id"`
	PostID int32 `json:"post_id"`
}

type Post struct {
	ID               int32          `json:"id"`
	ContentText      sql.NullString `json:"content_text"`
	ContentImagePath sql.NullString `json:"content_image_path"`
	UserID           int32          `json:"user_id"`
	Visible          bool           `json:"visible"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

type User struct {
	ID             int64     `json:"id"`
	HashedPassword string    `json:"hashed_password"`
	Salt           string    `json:"salt"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	DateOfBirth    time.Time `json:"date_of_birth"`
	Email          string    `json:"email"`
	UserName       string    `json:"user_name"`
}
